### PR TITLE
Date component and format license expiry date

### LINKED ISSUE #133: Instance Overview Expiry Date not formatted
**Describe the bug**
The expiry timestamp shown on the instance overview page is not formatted.

**To Reproduce**
1. Go to Admin -> Administration -> Overview 

**Expected behavior**
The expiry date should be formatted in a nice manner as other timestamps are. 

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome, Safari

### PR DESCRIPTION
**Pull request by DarthShmev**
This PR includes a new Date component which shows a relative time with an absolute formatted date as a tippy.

This PR closes #133 

I have included this new Date component per the following todo. https://github.com/wisp-gg/frontend/blob/02e4ab26e9c481d5ab7f781361e653bcb315b7b1/src/views/admin/LicenseInfo.vue#L52

Date component can be used like so: `<date :timestamp=x />`

Here are screenshots demonstrating the changes and the date component.

Before:
image

After:
image

### CODE REVIEW

File: src/views/admin/LicenseInfo.vue [hunk 1]
```diff
@@ -49,7 +49,7 @@
                             <skeleton :content="16">
                                 <t v-if="!license?.expiresAt" path="generic.never" />
 
-                                {{ license?.expiresAt }} <!-- TODO: <date :value="x" /> component? -->
+                                <date :timestamp="license?.expiresAt" />
```
Comment (victiondev) [inline src/views/admin/LicenseInfo.vue:52]: this would spit an error if license has no expiry - use <date v-if="license?.expiresAt" :timestamp="license?.expiresAt" />

File: src/components/Date.vue [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+</template>
+
+<script lang="ts">
+import { defineComponent, computed } from 'vue';
+import { formatDate, formatDateAbsolute } from '~/core/lang';
+
+export default defineComponent({
+    props: {
+        timestamp: {
+            type: String, Number,
```
Comment (victiondev) [inline src/components/Date.vue:14]: Should be type: String only (also thats invalid anyway should use an array) - but the formatDate functions only take a string

**Review by victiondev — CHANGES_REQUESTED** [review]

File: src/views/admin/LicenseInfo.vue (hunk 1 above)
Comment (DarthShmev) [reply src/views/admin/LicenseInfo.vue]: Good catch, fixed.

File: src/views/admin/LicenseInfo.vue [hunk 3]
```diff
@@ -49,7 +49,7 @@
                             <skeleton :content="16">
                                 <t v-if="!license?.expiresAt" path="generic.never" />
 
-                                {{ license?.expiresAt }} <!-- TODO: <date :value="x" /> component? -->
+                                <date v-else :timestamp="license?.expiresAt" />
```
Comment (victiondev) [inline src/views/admin/LicenseInfo.vue:52]: now im nitpicking but condition for existence should be first for consistency sake :mmlol: 

<date v-if="..." />
<t v-else />

**Review by victiondev — CHANGES_REQUESTED** [review]

File: src/views/admin/LicenseInfo.vue (hunk 3 above)
Comment (DarthShmev) [reply src/views/admin/LicenseInfo.vue]: All good 👍🏻 , changes have been made accordingly.
